### ISSUE TITLE
Create a nice 404 page

### ISSUE THREAD

**Issue by urish** [wokwi/good-arduino-code#11]
Sometimes people hit broken links, such as https://goodarduinocode.com/rofl 

Right now, they are presented with a boring 404 page. Let's put a smile on their faces!

Implementation notes: to create a 404 page in Next.js, simply create a `pages/404.tsx` file which default-exports a react component.

**Comment by LironHazan** [comment]
can you pls assign to me?

**Comment by urish** [comment]
Sure, thank you!
